package example

// Code generated by builder tool. DO NOT EDIT.

type PersonBuilder interface {
    Name(Name string) PersonBuilder
    Age(Age int) PersonBuilder
    Build() Person
}

type PersonBuilderImpl struct {
    Person Person
}

func NewPersonBuilder() PersonBuilder {
    return &PersonBuilderImpl{}
}

func (b *PersonBuilderImpl) Build() Person {
    return b.Person
}

func (b *PersonBuilderImpl) Name(Name string) PersonBuilder {
    b.Person.Name = Name
    return b
}

func (b *PersonBuilderImpl) Age(Age int) PersonBuilder {
    b.Person.Age = Age
    return b
}

